create_clock -period 10.000 [get_ports clk]
create_generated_clock -source [get_ports clk] -edges {1 2 3} -edge_shift {0.000 45.000 90.000} [get_ports -no_traverse clk_out1]
create_generated_clock -source [get_ports clk] -edges {1 2 3} -edge_shift {0.000 15.000 30.000} [get_ports -no_traverse clk_out2]
set_property -quiet IO_BUFFER_TYPE NONE [get_ports -quiet clk]
set_property -quiet IS_IP_OOC_CELL TRUE [get_cells -of [get_ports -no_traverse -quiet clk]]
